#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

APP="$1"
IMAGE="$2"
HOSTNAME=$(hostname -f)
LOCAL_USERNAME=`whoami`
ROLLBAR_TOKEN=$(dokku config:get "$APP" ROLLBAR_SERVER_API_KEY || dokku config:get "$APP" ROLLBAR_TOKEN)

if [[ $ROLLBAR_TOKEN ]]; then
  echo "-----> Notifying Rollbar ..."

  URL=$(dokku url $APP)
  ENVIRONMENT=$(dokku config:get "$APP" NODE_ENV || echo 'production')
  REVISION=$(cd $DOKKU_ROOT/$APP && git log -n 1 --pretty=format:"%H" 2>/dev/null)
  COMMENT=$(cd $DOKKU_ROOT/$APP && git log "$REVISION" -n1 --pretty='format:%s' 2> /dev/null || echo '')

  ROLLBAR_RESULT=$(curl -s https://api.rollbar.com/api/1/deploy/ \
    -F access_token=$ROLLBAR_TOKEN \
    -F environment=$ENVIRONMENT \
    -F revision=$REVISION \
    -F comment=$COMMENT \
    -F local_username=$LOCAL_USERNAME
  )

  echo "       ${ROLLBAR_RESULT}"
fi
